name: Maven Build

on:
  pull_request:

permissions:
  statuses: write  # ✅ ステータス更新の権限を追加

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Javaをセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Mavenでビルド
        run: mvn clean install

      - name: ビルドステータスをGitHubに通知
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;
            github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: "success",
              context: "maven-build",
              description: "Mavenビルド成功"
            });