name: Renovate

on:
  schedule:
    - cron: '0 * * * *'  # 1時間ごとに実行 (UTC)
  workflow_dispatch:  # 手動実行も可能

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Renovate を実行
        uses: renovatebot/github-action@v39.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
